### PR TITLE
Fix package

### PR DESCRIPTION
**Pull request by zeskeertwee**
make sure we only include the files we actually want to distrubute through crates.io

### CODE REVIEW

**Comment by zeskeertwee** [comment]
eeh, somehow the tests failed by changing the gitignore?

**Comment by zeskeertwee** [comment]
@sokorototo you got any clue what's going on?

**Comment by sokorototo** [comment]
I know what the problem is. This is because some tests expect the `simple/target.vach` and `signed/target.vach` to exist. Because they are now ignored, the tests auto-fail. Presumably with an os-error file not found error. If there was a way to run the `builder` tests before the fetch tests. We would be golden

**Comment by sokorototo** [comment]
Is there a way to run the tests in sequence?

**Comment by sokorototo** [comment]
Plus I do not know if the test environment has a semi-persistent filesystem. Anyway, I think we will have to run the `Builder` tests manually first.

**Comment by sokorototo** [comment]
Seems okay to me

**Review by sokorototo — APPROVED** [review]

**Pull request closed without merging**
