### PR TITLE
Renaming folders to match the names we discussed

### PR DESCRIPTION
**Pull request by sokorototo**
We agreed that we rename the folders to `vf`and `vach`. Because it is:
1. Easier to say and remember
2. Matches my branch better and
3. Reduces the hassle of merging my working branch with main

### CODE REVIEW

**Comment by zeskeertwee** [comment]
Yep! Seems perfectly fine to me!

**Comment by zeskeertwee** [comment]
Hmm, I don't think I can approve on mobile

**Review by zeskeertwee — APPROVED** [review]

**Comment by zeskeertwee** [comment]
Oh, I can!

**Comment by sokorototo** [comment]
Do you use the GitHub app? LOL, I usually just use it to browse cool projects

**Pull request merged**
