### PR TITLE
Take path into account for blob signature

### PR DESCRIPTION
**Pull request by zeskeertwee**
Append the path to the blob when computing the leaf's signature, also discard registry_signature to make code less complex.

### CODE REVIEW

**Comment by zeskeertwee** [comment]
TODO: tests don't pass yet

**Comment by sokorototo** [comment]
Kinda invalid since the folder names have changed, might need to re-iterate.

**Comment by zeskeertwee** [comment]
I think git can cope with files being moved, not 100% sure though.

**Review by sokorototo — COMMENTED** [review]
Seems ok, now check out my PR

**Comment by sokorototo** [comment]
Unable to merge somehow, no need as most of what is done here is already implemented in my Pull Request. The only difference being that I still have the HeaderConfig

**Comment by zeskeertwee** [comment]
i think i can solve the conflict

**Comment by sokorototo** [comment]
No need to, I have already solved the issue in my PR. Plus I need to get my progress on the `main` branch

**Comment by zeskeertwee** [comment]
as i said in #18, the conflics are basically the whole file, that isn't worth doing. We should just put the features in one-by-one.

**Comment by sokorototo** [comment]
Most changes are just files getting externalized. Maybe I document major changes: At the moment I just substituted my tests/mod.rs completely, as the other did not have any tests

**Comment by zeskeertwee** [comment]
i fixed the merge conflicts @sokorototo

**Comment by sokorototo** [comment]
Let me check the stuff, but tomorrow as i am on my phone.

**Comment by zeskeertwee** [comment]
Closing for the same reason as #18

**Pull request closed without merging**
